<a href="https://colab.research.google.com/github/prachynar/internetworking_project/blob/main/Internetworking_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [3]:
import kagglehub
path = kagglehub.dataset_download("chethuhn/network-intrusion-dataset")
print("Dataset:", path)

Using Colab cache for faster access to the 'network-intrusion-dataset' dataset.
Dataset: /kaggle/input/network-intrusion-dataset

In [4]:
import pandas as pd
import os
path = "/kaggle/input/network-intrusion-dataset"
os.listdir(path)

['Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
 'Tuesday-WorkingHours.pcap_ISCX.csv',
 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
 'Monday-WorkingHours.pcap_ISCX.csv',
 'Friday-WorkingHours-Morning.pcap_ISCX.csv',
 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
 'Wednesday-workingHours.pcap_ISCX.csv']

In [5]:
files = os.listdir(path)
dfs = []

for file in files:
  if file.endswith(".csv"):
    df = pd.read_csv(f"{path}/{file}")
    dfs.append(df)

data = pd.concat(dfs, ignore_index=True)

In [6]:
data.head(10)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,1266342,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,22,1319353,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,22,160,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,22,1303488,41,42,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,35396,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
5,22,244,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
6,22,1307239,41,40,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
7,60058,82,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
8,22,171,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
9,22,210,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [7]:
data.isna().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [8]:
data.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [9]:
data.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')

In [10]:
data.drop(columns=[' Packet Length Variance', ' Fwd Header Length.1', ' Bwd PSH Flags', 'Fwd PSH Flags',
                   ' Fwd URG Flags',' Bwd URG Flags','FIN Flag Count',' SYN Flag Count',
                   ' RST Flag Count',' PSH Flag Count',' ACK Flag Count',' URG Flag Count',
                   ' CWE Flag Count',' ECE Flag Count','Fwd Avg Bytes/Bulk',' Fwd Avg Packets/Bulk',
                   ' Fwd Avg Bulk Rate',' Bwd Avg Bytes/Bulk',' Bwd Avg Packets/Bulk','Bwd Avg Bulk Rate',
                   'Subflow Fwd Packets',' Subflow Fwd Bytes',' Subflow Bwd Packets',' Subflow Bwd Bytes',
                   'Init_Win_bytes_forward',' Init_Win_bytes_backward',' act_data_pkt_fwd',' min_seg_size_forward',
                   ' Active Std',' Active Max',' Active Min',' Idle Std',' Idle Max',' Idle Min', ' Fwd IAT Min',
                   'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
                   ' Bwd IAT Max', ' Bwd IAT Min', ' Fwd Header Length',
                   ' Bwd Header Length', ' Down/Up Ratio', ' Avg Fwd Segment Size',
                   ' Avg Bwd Segment Size', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', 'Bwd Packet Length Max',
                   ' Bwd Packet Length Min', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Min Packet Length',
                   ' Max Packet Length', 'Active Mean', 'Idle Mean', ' Destination Port', ' Fwd Packet Length Std',  ' Bwd Packet Length Std',
                   'Fwd Packets/s', ' Bwd Packets/s'], inplace=True)

In [16]:
data.columns

Index([' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Mean', ' Bwd Packet Length Mean', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', ' Packet Length Mean', ' Packet Length Std',
       ' Average Packet Size', ' Label'],
      dtype='object')

In [17]:
data

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label
0,1266342,41,44,2664,6954,64.975610,158.045455,7.595105e+03,67.122468,15075.50000,104051.399700,948537,0,111.837209,239.686848,113.152941,BENIGN
1,1319353,41,44,2664,6954,64.975610,158.045455,7.289937e+03,64.425518,15706.58333,104861.870100,955790,1,111.837209,239.686848,113.152941,BENIGN
2,160,1,1,0,0,0.000000,0.000000,0.000000e+00,12500.000000,160.00000,0.000000,160,160,0.000000,0.000000,0.000000,BENIGN
3,1303488,41,42,2728,6634,66.536585,157.952381,7.182268e+03,63.675308,15896.19512,106554.899000,956551,0,111.452381,241.642791,112.795181,BENIGN
4,77,1,2,0,0,0.000000,0.000000,0.000000e+00,38961.038960,38.50000,14.849242,49,28,0.000000,0.000000,0.000000,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830738,32215,4,2,112,152,28.000000,76.000000,8.194940e+03,186.248642,6443.00000,13617.579480,30780,3,41.714286,23.421602,48.666667,BENIGN
2830739,324,2,2,84,362,42.000000,181.000000,1.376543e+06,12345.679010,108.00000,183.597386,320,2,97.600000,76.133435,122.000000,BENIGN
2830740,82,2,1,31,6,15.500000,6.000000,4.512195e+05,36585.365850,41.00000,52.325902,78,4,17.000000,16.350331,22.666667,BENIGN
2830741,1048635,6,2,192,256,32.000000,128.000000,4.272221e+02,7.628965,149805.00000,375521.040500,1000947,1,53.333333,42.332021,60.000000,BENIGN
2830742,94939,4,2,188,226,47.000000,113.000000,4.360695e+03,63.198475,18987.80000,31664.102560,73049,1,65.857143,32.204702,76.833333,BENIGN

In [13]:
data.dtypes

 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
 Total Length of Bwd Packets      int64
 Fwd Packet Length Mean         float64
 Bwd Packet Length Mean         float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                     int64
 Flow IAT Min                     int64
 Packet Length Mean             float64
 Packet Length Std              float64
 Average Packet Size            float64
 Label                           object
dtype: object

In [15]:
data = data.astype({' Label':'category'})
data.dtypes

 Flow Duration                     int64
 Total Fwd Packets                 int64
 Total Backward Packets            int64
Total Length of Fwd Packets        int64
 Total Length of Bwd Packets       int64
 Fwd Packet Length Mean          float64
 Bwd Packet Length Mean          float64
Flow Bytes/s                     float64
 Flow Packets/s                  float64
 Flow IAT Mean                   float64
 Flow IAT Std                    float64
 Flow IAT Max                      int64
 Flow IAT Min                      int64
 Packet Length Mean              float64
 Packet Length Std               float64
 Average Packet Size             float64
 Label                          category
dtype: object